---
title: "dplyr and Gapminder"
author: "Adam Nielsen"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:  
    keep_md: true
    toc: true
    toc_float: true
    code_folding: hide
    fig_height: 6
    fig_width: 12
    fig_align: 'center'
---

```{r, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r load_libraries, include=FALSE}
# Use this R-Chunk to load all your libraries!
#install.packages("tidyverse") # run this line once in console to get package
library(tidyverse)
library(gapminder)

```

```{r load_data}
# Use this R-Chunk to import all your datasets!
gapminder
glimpse(gapminder)
```

## Background

_Place Task Background Here_

## Data Wrangling

```{r tidy_data}
# Use this R-Chunk to clean & wrangle your data!
data = filter(gapminder, country != "Kuwait") %>%
  group_by(continent, year) %>%
  mutate(mean_gdp_percontinent = weighted.mean(gdpPercap, pop)) %>%
  ungroup()
```

## Data Visualization

```{r plot_data}
# Use this R-Chunk to plot & visualize your data!
ggplot(data) +
  geom_point(mapping = aes(x = year,
                           y = gdpPercap,
                           size = pop / 100000,
                           group = country,
                           color = continent)) +
  geom_line(mapping = aes(x = year,
                           y = gdpPercap,
                           group = country,
                           color = continent)) +
  geom_line(mapping = aes(x = year,
                           y = mean_gdp_percontinent)) +
  geom_point(mapping = aes(x = year,
                           y = mean_gdp_percontinent,
                           size = pop / 100000)) +
  facet_grid(~ continent) +
  labs(x = "Year", y = "GDP per capita", color = "Continent", size = "Population (100k)")

data %>%
  filter(continent %in% c("Africa", "Americas", "Asia")) %>%
  group_by(country) %>%
  filter(year == c(1952, 2007)) %>%
  mutate(lifeExp_dif = abs(lifeExp - lag(lifeExp))) %>%
  ungroup() %>%
  group_by(continent) %>%
  filter(lifeExp_dif %in% range(lifeExp_dif, na.rm = TRUE)) %>%
  ungroup() %>%
  ggplot(aes(x = reorder(country, -lifeExp_dif), y = lifeExp_dif, fill = continent)) + 
  geom_bar(stat = "identity") +
  labs(y = "Difference in life expectancy 1952-2007", x = "Country")
```

## Conclusions
