---
title: "Data to answer questions"
author: "Adam Nielsen"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:  
    keep_md: true
    toc: true
    toc_float: true
    code_folding: hide
    fig_height: 6
    fig_width: 12
    fig_align: 'center'
---

```{r, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r load_libraries, include=FALSE}
# Use this R-Chunk to load all your libraries!
#install.packages("tidyverse") # run this line once in console to get package
library(tidyverse)

```

```{r load_data}
# Use this R-Chunk to import all your datasets!
adaptations <- read_csv("Books into Movies.csv")
## https://www.kaggle.com/padmanabh275/books-into-movies

movies <- read_csv("IMDb movies.csv")
##https://www.kaggle.com/stefanoleone992/imdb-extensive-dataset?select=IMDb+movies.csv

books <- read_csv("books.csv")
##https://www.kaggle.com/jealousleopard/goodreadsbooks

book_length <- read_csv("book length movie length raw data - scatter.csv")
##https://www.overthinkingit.com/2013/08/12/book-word-count-movie-length-2/
``` 

## Background

_Place Task Background Here_

## Data Wrangling

```{r tidy_data}
# Use this R-Chunk to clean & wrangle your data!
book_length %>%
  glimpse() %>%
  ggplot(mapping = aes(y = `IMDB ranking`, x = `Book length (words)`)) +
  geom_jitter()
```

## Data Visualization

```{r plot_data}
# Use this R-Chunk to plot & visualize your data!

```

## Conclusions
