---
title: "TASK 15"
author: "Adam Nielsen"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:  
    keep_md: true
    toc: true
    toc_float: true
    code_folding: hide
    fig_height: 6
    fig_width: 12
    fig_align: 'center'
---

```{r, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r load_libraries, include=FALSE}
# Use this R-Chunk to load all your libraries!
#install.packages("tidyverse") # run this line once in console to get package
library(tidyverse)
library(stringr)
```

```{r load_data}
# Use this R-Chunk to import all your datasets!
rletters <- read_lines("https://byuistats.github.io/M335/data/randomletters.txt")
rletters_plus <- read_lines("https://byuistats.github.io/M335/data/randomletters_wnumbers.txt")
```

## Background

_Place Task Background Here_

## Data Wrangling

```{r tidy_data}
# Use this R-Chunk to clean & wrangle your data!
seq1700 <- seq(0, str_length(rletters), 1700)
seq1700[1] = 1
every1700 <- rletters %>%
  str_sub(start = seq1700, end = seq1700)

every1700

num_to_letter <- rletters_plus %>%
  str_extract_all("\\d+") %>%
  unlist()

num_to_letter <- LETTERS[as.numeric(num_to_letter)]

num_to_letter

vowels <- rletters %>%
  str_remove_all("\ |\\.") %>%
  str_extract_all("[aeiou]+") %>%
  unlist() %>%
  .[which.max(str_length(.))]

vowels
```

## Data Visualization

```{r plot_data}
# Use this R-Chunk to plot & visualize your data!

```

## Conclusions
