---
title: "CASE STUDY TITLE"
author: "YOUR NAME"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:  
    keep_md: true
    toc: true
    toc_float: true
    code_folding: hide
    fig_height: 6
    fig_width: 12
    fig_align: 'center'
---

```{r, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r load_libraries, include=FALSE}
# Use this R-Chunk to load all your libraries!
#install.packages("tidyverse") # run this line once in console to get package
library(tidyverse)

```

```{r load_data}
# Use this R-Chunk to import all your datasets!
covid_dat <- read_csv("https://github.com/ktoutloud/classslides/raw/master/math335/data/M335_excess-mortality-p-scores.csv") %>%
  glimpse()
```

## Background

_Place Task Background Here_

## Data Wrangling

```{r tidy_data}
# Use this R-Chunk to clean & wrangle your data!
covid_dat <- covid_dat %>%
  mutate(Spain = Spain * 100) %>%
  pivot_longer(cols = -date, names_to = "Country", values_to = "excess_mortality") %>%
  glimpse()


```

## Data Visualization

```{r plot_data}
# Use this R-Chunk to plot & visualize your data!
covid_dat %>%
  filter(Country == c("England & Wales", "Germany", "Spain", "Norway")) %>%
ggplot(aes(y = excess_mortality, x = date, group = Country, color = Country)) + 
  geom_line() +
  geom_point()
  
```

## Conclusions
